### PR TITLE
update demo

### PR DESCRIPTION
**Pull request by ftshijt**

### CODE REVIEW

**Comment by sw005320** [comment]
LGTM.
Can you merge it if it is ready?

**Comment by ftshijt** [comment]
> LGTM.
> Can you merge it if it is ready?

Yes, I think it's ready, but I do not have the `write access` to this repo, could you please merge it?

**Comment by sw005320** [comment]
done!

**Comment by sw005320** [comment]
Maybe we can also add RTF? (but if it is too slow, we may not have to...)

**Pull request merged**
