### PR TITLE
Add speech enhancement demo

### PR DESCRIPTION
**Pull request by LiChenda**
The demo notebook is download from the [colab page](https://colab.research.google.com/drive/1fjRJCh96SoYLZPRxsjF9VDv4Q2VoIckI?usp=sharing).

### CODE REVIEW

**Comment by sw005320** [comment]
- Like https://colab.research.google.com/github/espnet/notebook/blob/master/espnet2_asr_realtime_demo.ipynb, it would better to have a function to upload the audios and enhance it.
- Can you add a single channel enhancement example as well? We usually don't have multichannel signals.
- Like https://colab.research.google.com/github/espnet/notebook/blob/master/espnet2_tts_realtime_demo.ipynb, it would be better to switch the various models, e.g., CHiME-4 various models for enhancement, various speech separation models trained with various corpora.
- https://colab.research.google.com/github/espnet/notebook/blob/master/espnet2_asr_realtime_demo.ipynb, it would be better to exclude the executed log.

**Comment by sw005320** [comment]
If it is too complicated, you can separate the notebook with enhancement and separation.

**Comment by sw005320** [comment]
- For the ASR evaluation, could you exclude ` <NOISE>` in the evaluation?

**Comment by LiChenda** [comment]
> * Like https://colab.research.google.com/github/espnet/notebook/blob/master/espnet2_asr_realtime_demo.ipynb, it would better to have a function to upload the audios and enhance it

It's supported now.

> * Can you add a single channel enhancement example as well? We usually don't have multichannel signals.

It's included now.

> * Like https://colab.research.google.com/github/espnet/notebook/blob/master/espnet2_tts_realtime_demo.ipynb, it would be better to switch the various models, e.g., CHiME-4 various models for enhancement, various speech separation models trained with various corpora.

Hi @sw005320 , currently, we do not have many single-speaker enhancement models in model zoo, so I only add this choice function in the separation demo.

> * https://colab.research.google.com/github/espnet/notebook/blob/master/espnet2_asr_realtime_demo.ipynb, it would be better to exclude the executed log

The logs are removed now.

**Comment by LiChenda** [comment]
> * For the ASR evaluation, could you exclude ` <NOISE>` in the evaluation?

It's removed now.

**Comment by sw005320** [comment]
Perfect!
We can add vctk_noisyreverb and dns models (by @ChiaYu-Chang later) in this colab, later!

**Pull request merged**
