### PR TITLE
Add ESPnetEZ

### PR DESCRIPTION
**Pull request by Masao-Someki**
I added some examples in ESPnetEZ folder.
I will add demos for the following tasks:

- [x] ASR
- [x] ST
- [x] SLU

### CODE REVIEW

**Comment by Masao-Someki** [comment]
@juice500ml 
I’ve added several notebooks from my experiments. They worked in the cluster environment, and I’ve copied them over and added descriptions.

Could you review the contents and directory structure?

I also realized that I didn't push several important implementations related these files, such as `espnetez.preprocess.add_special_tokens` for adding new special tokens to the tokenizer, converter, and Embedding layer for pretrained models.
I will check my experimental code and push everything required.

**Comment by juice500ml** [comment]
Sounds awesome, will check within today!

**Comment by Masao-Someki** [comment]
Currently I am working on this PR, and I need to modify the ST notebook a little. I will update after everything has finished..

https://github.com/espnet/espnet/pull/5890

**Comment by Masao-Someki** [comment]
ST recipes has fixed now, (and I checked on Google colab) so I think this PR is ready for merge now

**Pull request merged**
